#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; ALLOWED_ROOT=/Users/taejunoh/Developer/LFG
PUBLIC_ZIP=; ACCEPTANCE_APP=; FIXTURE_ROOT=; EVIDENCE_ROOT=; CASE=; MANIFEST=; RUNTIME_FIXTURE=; ACCEPTANCE_PID=
usage() { echo 'usage: native-acceptance-run.sh --public-zip PATH --acceptance-app PATH --fixtures-root DIR --evidence-root DIR --case CASE' >&2; }
fail() { echo "native-acceptance-run: $*" >&2; exit 64; }
cap() { "$@" 2>&1 | head -c 1048576; }
record() { local name="$1" code="$2" status="$3"; printf '%s\t%s\t%s\n' "$name" "$code" "$status" >> "$MANIFEST"; }
fail_step() { record "$1" "$2" "$3"; exit "$3"; }
cleanup() { local status=$?; trap - EXIT INT TERM; if [[ -n "$ACCEPTANCE_PID" ]] && kill -0 "$ACCEPTANCE_PID" 2>/dev/null; then kill "$ACCEPTANCE_PID" 2>/dev/null || true; wait "$ACCEPTANCE_PID" 2>/dev/null || true; fi; [[ -z "$RUNTIME_FIXTURE" ]] || rm -f -- "$RUNTIME_FIXTURE"; exit "$status"; }
trap cleanup EXIT INT TERM
while (($#)); do case "$1" in --public-zip) [[ -z "$PUBLIC_ZIP" ]] || fail 'duplicate --public-zip'; shift; (($#)) || fail 'missing --public-zip value'; PUBLIC_ZIP="$1" ;; --acceptance-app) [[ -z "$ACCEPTANCE_APP" ]] || fail 'duplicate --acceptance-app'; shift; (($#)) || fail 'missing --acceptance-app value'; ACCEPTANCE_APP="$1" ;; --fixtures-root) [[ -z "$FIXTURE_ROOT" ]] || fail 'duplicate --fixtures-root'; shift; (($#)) || fail 'missing --fixtures-root value'; FIXTURE_ROOT="$1" ;; --evidence-root) [[ -z "$EVIDENCE_ROOT" ]] || fail 'duplicate --evidence-root'; shift; (($#)) || fail 'missing --evidence-root value'; EVIDENCE_ROOT="$1" ;; --case) [[ -z "$CASE" ]] || fail 'duplicate --case'; shift; (($#)) || fail 'missing --case value'; CASE="$1" ;; -h|--help) usage; exit 0 ;; *) fail "unknown option: $1" ;; esac; shift; done
[[ -n "$PUBLIC_ZIP" && -n "$ACCEPTANCE_APP" && -n "$FIXTURE_ROOT" && -n "$EVIDENCE_ROOT" && -n "$CASE" ]] || { usage; exit 64; }
for path in "$PUBLIC_ZIP" "$ACCEPTANCE_APP" "$FIXTURE_ROOT" "$EVIDENCE_ROOT"; do [[ "$path" == /* ]] || fail 'all paths must be absolute'; done
real_path() { realpath "$1" 2>/dev/null; }
public_real="$(real_path "$PUBLIC_ZIP")" || fail 'public ZIP path is not resolvable'; app_real="$(real_path "$ACCEPTANCE_APP")" || fail 'acceptance app path is not resolvable'; fixtures_real="$(real_path "$FIXTURE_ROOT")" || fail 'fixtures root path is not resolvable'; evidence_real="$(real_path "$EVIDENCE_ROOT" 2>/dev/null || true)"; [[ -n "$evidence_real" ]] || evidence_real="$(realpath "$(dirname "$EVIDENCE_ROOT")")/$(basename "$EVIDENCE_ROOT")"
for path in "$public_real" "$app_real" "$fixtures_real" "$evidence_real"; do [[ "$path" == "$ALLOWED_ROOT" || "$path" == "$ALLOWED_ROOT"/* ]] || fail 'path must remain below approved root'; done
[[ "$public_real" != "$app_real" ]] || fail 'public ZIP and acceptance app resolve to the same path'; [[ -f "$PUBLIC_ZIP" ]] || fail 'public ZIP must be a regular file'; [[ -d "$ACCEPTANCE_APP" ]] || fail 'acceptance app must be a bundle directory'; [[ -d "$FIXTURE_ROOT" ]] || fail 'fixtures root must be a directory'
if [[ -e "$EVIDENCE_ROOT" ]]; then [[ -d "$EVIDENCE_ROOT" ]] || fail 'evidence root must be a directory'; [[ -z "$(find "$EVIDENCE_ROOT" -mindepth 1 -print -quit)" ]] || fail 'evidence root must be empty'; else mkdir -p "$EVIDENCE_ROOT"; fi
MANIFEST="$EVIDENCE_ROOT/manifest.tsv"; printf 'step\tcode\tstatus\n' > "$MANIFEST"
command -v sw_vers >/dev/null 2>&1 || fail_step preflight nativeToolUnavailable 69; os_version="$(sw_vers -productVersion 2>/dev/null || true)"; [[ "$os_version" == 14.* ]] || fail_step preflight nativeUnsupportedOS 70; [[ "$(uname -m 2>/dev/null || true)" == arm64 ]] || fail_step preflight nativeUnsupportedArchitecture 71; command -v networksetup >/dev/null 2>&1 || fail_step preflight nativeToolUnavailable 69
for service in $(networksetup -listallnetworkservices 2>/dev/null | sed '/^An asterisk/d; /^\*/d'); do [[ "$(networksetup -getnetworkserviceenabled "$service" 2>/dev/null || true)" != *Enabled* ]] || fail_step preflight nativeNetworkEnabled 72; done
case_template() { case "$1" in parser-malformed) echo "$ROOT/Fixtures/acceptance/native-driver/parser/malformed.json" ;; parser-truncated|parser-over-boundary) echo "$ROOT/Fixtures/acceptance/native-driver/widget/baseline-update.json" ;; parser-unknown-schema) echo "$ROOT/Fixtures/acceptance/native-driver/parser/unknown-schema.json" ;; parser-unknown-id) echo "$ROOT/Fixtures/acceptance/native-driver/parser/unknown-id.json" ;; widget-*) echo "$ROOT/Fixtures/acceptance/native-driver/widget/$1.json" ;; notification-off) echo "$ROOT/Fixtures/acceptance/native-driver/notification/off.json" ;; notification-denied) echo "$ROOT/Fixtures/acceptance/native-driver/notification/deny.json" ;; notification-revoked) echo "$ROOT/Fixtures/acceptance/native-driver/notification/revoke.json" ;; notification-*) echo "$ROOT/Fixtures/acceptance/native-driver/notification/${1#notification-}.json" ;; *) return 1 ;; esac; }
source_template="$(case_template "$CASE")" || fail_step fixture fixtureUnknownCase 64; [[ -f "$source_template" ]] || fail_step fixture fixtureMissingTemplate 66; RUNTIME_FIXTURE="$FIXTURE_ROOT/runtime-$CASE.json"; cp -- "$source_template" "$RUNTIME_FIXTURE"
start_at="$(date -u '+%Y-%m-%dT%H:%M:%S.000Z')"; local_day="$(date '+%Y-%m-%d')"; sed -i '' -e "s/2026-09-01T12:00:00.000Z/$start_at/g" -e "s/2026-09-02T12:00:00.000Z/$start_at/g" -e "s/2026-09-01/$local_day/g" "$RUNTIME_FIXTURE" 2>/dev/null || sed -i -e "s/2026-09-01T12:00:00.000Z/$start_at/g" -e "s/2026-09-02T12:00:00.000Z/$start_at/g" -e "s/2026-09-01/$local_day/g" "$RUNTIME_FIXTURE"
[[ "$CASE" != parser-truncated ]] || truncate -s -1 "$RUNTIME_FIXTURE"; if [[ "$CASE" == parser-over-boundary ]]; then size="$(wc -c < "$RUNTIME_FIXTURE" | tr -d ' ')"; (( size < 262145 )) || fail_step fixture fixtureTooLarge 67; printf '%*s' "$((262145 - size))" '' >> "$RUNTIME_FIXTURE"; fi; size="$(wc -c < "$RUNTIME_FIXTURE" | tr -d ' ')"; (( size <= 262144 )) || fail_step fixture fixtureTooLarge 67; digest="$(shasum -a 256 "$RUNTIME_FIXTURE" | awk '{print $1}')"; record fixture fixtureReady 0
if [[ "$CASE" == parser-* ]]; then set +e; NEEDLBAR_ACCEPTANCE_INPUT_ROOT="$FIXTURE_ROOT" "$ACCEPTANCE_APP/Contents/MacOS/Needlbar" --acceptance-fixture "$RUNTIME_FIXTURE" >"$EVIDENCE_ROOT/parser.stdout" 2>"$EVIDENCE_ROOT/parser.stderr"; status=$?; set -e; [[ "$status" -ne 0 ]] || fail_step parser fixtureUnexpectedSuccess 68; code="$(head -n 1 "$EVIDENCE_ROOT/parser.stderr" | tr -cd '[:alnum:]_')"; [[ -n "$code" ]] || code=fixtureMalformedJSON; record parser "$code" "$status"; else [[ -x "$ACCEPTANCE_APP/Contents/MacOS/Needlbar" ]] || fail_step launch nativeAcceptanceExecutableMissing 73; NEEDLBAR_ACCEPTANCE_INPUT_ROOT="$FIXTURE_ROOT" "$ACCEPTANCE_APP/Contents/MacOS/Needlbar" --acceptance-fixture "$RUNTIME_FIXTURE" >"$EVIDENCE_ROOT/runtime.stdout" 2>"$EVIDENCE_ROOT/runtime.stderr" & ACCEPTANCE_PID=$!; set +e; wait "$ACCEPTANCE_PID"; status=$?; set -e; ACCEPTANCE_PID=; [[ "$status" -eq 0 ]] || fail_step launch nativeAcceptanceFailed "$status"; record launch accepted 0; fi
printf 'case=%s\tfixtureSchema=1\tfixtureDigest=%s\tos=%s\tarch=arm64\toutcome=recorded\n' "$CASE" "$digest" "$os_version" >> "$MANIFEST"; echo 'native acceptance harness completed'
